name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.2

      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish
